name: Run UI Acceptance Tests

on:
  # Run manually or on a pull request to main
  workflow_dispatch:

  pull_request:
      branches:
        - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Create .env file
        run: |
            echo SQUARE_ACCESS_TOKEN=fake >> .env
            echo SQUARE_API_URL=fake >> .env
            echo SQUARE_API_VERSION=fake >> .env
            echo SQUARE_ENVIRONMENT=fake >> .env
            echo VITE_USE_MOCK_API=true >> .env

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests (with virtual display)
        run: xvfb-run --auto-servernum npx playwright test

      - name: Upload Playwright test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results
